name = "svelte-kit-shopify"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx drizzle-kit generate"
dev = "npx drizzle-kit migrate deploy && pnpm exec vite:dev"
